### ISSUE TITLE
pyNekketsu doesn't launch on Arch Linux

### ISSUE THREAD

**Issue by malespiaut** [jmimu/pyNekketsu#2]
Hello,

Cloning the git repo, and launching `python pyNekketsu.py` returns the following error:

```
pygame 2.1.2 (SDL 2.26.2, Python 3.10.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/tmp/pyNekketsu/pyNekketsu.py", line 31, in <module>
    from retrogamelib import display
  File "/tmp/pyNekketsu/retrogamelib/__init__.py", line 1, in <module>
    import display, button, dialog, gameobject, clock, font, util, constants, camera
ModuleNotFoundError: No module named 'display'
```

I've tried fixing it by hand, without success. I'm sure that's an easy fix, but I can't figure it out.

**Comment by jmimu** [comment]
Hello,
I updated retrogamelib, it should work now.

**Comment by pmgallardo** [comment]
I am having the same issue on Ubuntu after downloading latest version.

**Comment by pmgallardo** [comment]
I tried it today and it works in Ubuntu 23.04, running from both terminal and PyCharm.
